apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: deliverystore
spec:
  type: state.in-memory
  version: v1
  metadata: []
# spec:
#   type: state.redis
#   version: v1
#   metadata:
#   - name: redisHost
#     value: localhost:6379
#   - name: redisPassword
#     value: ""
#   - name: actorStateStore
#     value: "true"